In [1]:
import pandas as pd

In [7]:
us_babies = pd.read_csv('us_baby_names.csv')

In [9]:
us_babies

              Id       Name  Year Gender  Count
0              1       Mary  1880      F   7065
1              2       Anna  1880      F   2604
2              3       Emma  1880      F   2003
3              4  Elizabeth  1880      F   1939
4              5     Minnie  1880      F   1746
...          ...        ...   ...    ...    ...
1825428  1825429     Zykeem  2014      M      5
1825429  1825430     Zymeer  2014      M      5
1825430  1825431    Zymiere  2014      M      5
1825431  1825432      Zyran  2014      M      5
1825432  1825433      Zyrin  2014      M      5

[1825433 rows x 5 columns]

In [11]:
us_babies['Gender']

0          F
1          F
2          F
3          F
4          F
          ..
1825428    M
1825429    M
1825430    M
1825431    M
1825432    M
Name: Gender, Length: 1825433, dtype: object

In [14]:
us_babies['Gender']=='M'

0          False
1          False
2          False
3          False
4          False
           ...
1825428     True
1825429     True
1825430     True
1825431     True
1825432     True
Name: Gender, Length: 1825433, dtype: bool

In [15]:
us_babies_Male = us_babies.loc[us_babies['Gender']=='M', :]

In [26]:
us_babies_Male

              Id     Name  Year Gender  Count
942          943     John  1880      M   9655
943          944  William  1880      M   9532
944          945    James  1880      M   5927
945          946  Charles  1880      M   5348
946          947   George  1880      M   5126
...          ...      ...   ...    ...    ...
1825428  1825429   Zykeem  2014      M      5
1825429  1825430   Zymeer  2014      M      5
1825430  1825431  Zymiere  2014      M      5
1825431  1825432    Zyran  2014      M      5
1825432  1825433    Zyrin  2014      M      5

[743750 rows x 5 columns]

In [28]:
sort_us_babies = us_babies_Male.sort_values('Count', ascending = False)

In [29]:
sort_us_babies

              Id      Name  Year Gender  Count
437157    437158     James  1947      M  94755
544602    544603   Michael  1957      M  92709
437158    437159    Robert  1947      M  91642
533139    533140   Michael  1956      M  90633
556176    556177   Michael  1958      M  90519
...          ...       ...   ...    ...    ...
1093735  1093736    Moussa  1990      M      5
1093736  1093737  Moustafa  1990      M      5
1093737  1093738     Murry  1990      M      5
1093738  1093739     Myers  1990      M      5
1825432  1825433     Zyrin  2014      M      5

[743750 rows x 5 columns]

In [30]:
sort_us_babies.iloc[0:5]

            Id     Name  Year Gender  Count
437157  437158    James  1947      M  94755
544602  544603  Michael  1957      M  92709
437158  437159   Robert  1947      M  91642
533139  533140  Michael  1956      M  90633
556176  556177  Michael  1958      M  90519